batch_size: 300
epochs: 30
labels_for_driven_positive_and_negative_pairs:
wandb_project_name: BIOSCAN-CLIP-uni-model-image
using_train_seen_for_pre_train: true
dataset: bioscan_1m

image:
  model: vit

model_output_name: image_simclr_style_bioscan_1m
port: 29531
#
#lr_scheduler: one_cycle
lr_config:
  lr: 1e-6
  max_lr: 5e-5
weight_decay: 1e-4

temperature: 0.07
n_views: 2

#all_gather: true
#loss_setup:
#  gather_with_grad: true
#  use_horovod: false
#  local_loss: false
#fix_temperature: false
#amp: true

random_seed: false
default_seed: 42

log_every_n_steps: 500