batch_size: 400
epochs: 160
labels_for_driven_positive_and_negative_pairs:
wandb_project_name: BIOSCAN-CLIP-INSECT
dataset: INSECT

image:
  input_type: image
  model: lora_vit
dna:
  input_type: sequence
  model: lora_barcode_bert
language:
  input_type: sequence
  model: lora_bert

model_output_name: trained_with_insect_image_dna_text
evaluation_period: 50
ckpt_path: ${project_root_path}/ckpt/bioscan_clip/trained_with_bioscan_1m/image_dna_text.pth
ckpt_trained_with_insect_image_dna_text_path: ${project_root_path}/ckpt/bioscan_clip/trained_with_insect_image_dna_text
output_dim: 768
port: 29501

