batch_size: 200
epochs: 15
labels_for_driven_positive_and_negative_pairs:
wandb_project_name: BIOSCAN-CLIP-5M
using_train_seen_for_pre_train: true
dataset: bioscan_5m
pre_train_for_barcode_bert: CANADA-1.5M_old
image:
  input_type: image
  pre_train_model: vit_base_patch16_224
dna:
  input_type: sequence
  pre_train_model: barcode_bert
language:
  input_type: sequence
  pre_train_model: prajjwal1/bert-small

model_output_name: image_dna_text_4gpu
evaluation_period: 3

output_dim: 768
port: 29531

disable_lora: true
lr_scheduler: one_cycle
lr_config:
  lr: 1e-6
  max_lr: 5e-5

all_gather: true
loss_setup:
  gather_with_grad: true
  use_horovod: false
  local_loss: false
fix_temperature: false
amp: true

random_seed: false

eval_skip_epoch: -1

default_seed: 42

fine_tuning_set:
  batch_size: 150
  epochs: 15
  fine_tune_model_output_dir: ${model_output_dir}/${model_config.model_output_name}/supervise_fine_tune_ckpt