batch_size: 300
epochs: 15
labels_for_driven_positive_and_negative_pairs:
wandb_project_name: BIOSCAN-CLIP-small_experiments_test_lora
using_train_seen_for_pre_train: true
dataset: bioscan_1m

image:
  input_type: image
  model: vit
dna:
  input_type: sequence
  model: barcode_bert
language:
  input_type: sequence
  model: bert_small

model_output_name: test_lora_lora_experiment
evaluation_period: 1
ckpt_path: ${project_root_path}/ckpt/bioscan_clip/full_fine_tuning_one_cycle_lr_sche_with_all_gather/image_dna_text.pth
output_dim: 768
port: 29505

disable_lora: false
lr_scheduler: one_cycle
lr_config:
  lr: 0.000001
  max_lr: 0.00005

all_gather: true
loss_setup:
  gather_with_grad: true
  use_horovod: false
  local_loss: false
amp: true

random_seed: false

eval_skip_epoch: 23

default_seed: 42
