batch_size: 400
epochs: 4
wandb_project_name: BIOSCAN-CLIP-5M
using_train_seen_for_pre_train: true
dataset: bioscan_5m

image:
  input_type: image
  pre_train_model: vit_base_patch16_224
dna:
  input_type: sequence
  pre_train_model: barcode_bert
language:
  input_type: sequence
  pre_train_model: prajjwal1/bert-small

load_ckpt: false
model_output_name: no_align_5m
evaluation_period: 1
ckpt_path: ${project_root_path}/ckpt/bioscan_clip/trained_with_bioscan_5m/image_dna_text.pth
output_dim: 768
port: 12316