batch_size: 200
epochs: 15
wandb_project_name: BIOSCAN-CLIP-ablation_with_open_clip
using_train_seen_for_pre_train: true
dataset: bioscan_1m

image:
  input_type: image
  model: vit
  pre_train_model: vit_large_patch16_224
dna:
  input_type: sequence
  model: barcode_bert
language:
  input_type: sequence
  model: bert_small
  pre_train_model: bert-base-uncased

model_output_name: trained_with_bioscan_1m_image_dna_text_without_open_clip_vit_large_patch16_224
evaluation_period: 1
ckpt_path: ${project_root_path}/ckpt/bioscan_clip/new_ckpt_from_rerun/other_experiments/open_clip_ablations/5_without_open_clip_base_uncased/best.pth
output_dim: 768
port: 12348

disable_lora: true
lr_scheduler: one_cycle
lr_config:
  lr: 0.000001
  max_lr: 0.00005

all_gather: true
loss_setup:
  gather_with_grad: true
  use_horovod: false
  local_loss: false

eval_skip_epoch: 10

fix_temperature: true
amp: true
