batch_size: 200
epochs: 15
wandb_project_name: BIOSCAN-CLIP
using_train_seen_for_pre_train: true
dataset: bioscan_1m

image:
  input_type: image
  model: vit
dna:
  input_type: sequence
  model: barcode_bert
language:
  input_type: sequence
  model: bert_small

model_output_name: image_dna_text_random_seed_no_3
evaluation_period: 1
output_dim: 768
port: 29533

disable_lora: true
lr_scheduler: one_cycle
lr_config:
  lr: 1e-6
  max_lr: 5e-5

all_gather: true
loss_setup:
  gather_with_grad: true
  use_horovod: false
  local_loss: false
fix_temperature: false
amp: true

random_seed: true

eval_skip_epoch: 10

fine_tuning_set:
  batch_size: 150
  epochs: 15
  fine_tune_model_output_dir: ${model_output_dir}/${model_config.model_output_name}/supervise_fine_tune_ckpt